#!/usr/bin/env python3
##
# @file test_grasp_action.py
#
# @brief Unit tests for GraspAction.
#
# @section author Author(s)
# - Created by chuoru on 2026/06/19.
#
# Copyright (c) 2026 HACHIX.  All rights reserved.

# Standard library
import threading
import unittest
from unittest.mock import MagicMock, call, patch

# Internal library
from actions.base import ActionState
from actions.grasp import GraspAction


class _GraspTestMixin:
    def setUp(self):
        self._logger_patcher = patch("actions.base.Logger")
        self._logger_patcher.start()
        self._controller = MagicMock()
        self._controller.execute.return_value = True

    def tearDown(self):
        self._logger_patcher.stop()

    def _make(self, device_name="left_hand", grasp_level=1, torque_limit=180):
        return GraspAction(self._controller, device_name, grasp_level, torque_limit)


class TestGraspActionInit(_GraspTestMixin, unittest.TestCase):
    """Tests for GraspAction construction and validation."""

    def test_initial_state_is_idle(self):
        self.assertEqual(self._make().state(), ActionState.IDLE)

    def test_invalid_grasp_level_zero_raises(self):
        with self.assertRaises(ValueError):
            GraspAction(self._controller, "left_hand", 0, 180)

    def test_invalid_grasp_level_five_raises(self):
        with self.assertRaises(ValueError):
            GraspAction(self._controller, "left_hand", 5, 180)

    def test_valid_grasp_levels_accepted(self):
        for level in (1, 2, 3, 4):
            action = GraspAction(self._controller, "left_hand", level, 128)
            self.assertIsNotNone(action)

    def test_torque_limit_negative_raises(self):
        with self.assertRaises(ValueError):
            GraspAction(self._controller, "left_hand", 1, -1)

    def test_torque_limit_over_255_raises(self):
        with self.assertRaises(ValueError):
            GraspAction(self._controller, "left_hand", 1, 256)

    def test_torque_limit_boundary_zero_accepted(self):
        action = GraspAction(self._controller, "left_hand", 1, 0)
        self.assertIsNotNone(action)

    def test_torque_limit_boundary_255_accepted(self):
        action = GraspAction(self._controller, "left_hand", 1, 255)
        self.assertIsNotNone(action)


class TestGraspActionParameters(_GraspTestMixin, unittest.TestCase):
    """Tests for GraspAction.parameters()."""

    def test_parameters_returns_device_name(self):
        self.assertEqual(self._make(device_name="hand_a").parameters()["device_name"], "hand_a")

    def test_parameters_returns_grasp_level(self):
        self.assertEqual(self._make(grasp_level=3).parameters()["grasp_level"], 3)

    def test_parameters_returns_torque_limit(self):
        self.assertEqual(self._make(torque_limit=200).parameters()["torque_limit"], 200)

    def test_parameters_contains_exactly_three_keys(self):
        self.assertEqual(
            set(self._make().parameters().keys()),
            {"device_name", "grasp_level", "torque_limit"},
        )


class TestGraspActionPoses(_GraspTestMixin, unittest.TestCase):
    """Tests for pose arrays generated by _build_poses() via controller dispatch."""

    def _run_and_get_move_calls(self, level):
        action = self._make(grasp_level=level)
        action.start()
        action.wait(timeout=2.0)
        move_calls = [
            c for c in self._controller.execute.call_args_list
            if c[0][1] == "move"
        ]
        return [c[0][2] for c in move_calls]

    def test_level1_prepare_thumb_yaw_in(self):
        prepare, _ = self._run_and_get_move_calls(1)
        self.assertEqual(prepare[1], 255)  # thumb_cmc_yaw

    def test_level1_prepare_index_half(self):
        prepare, _ = self._run_and_get_move_calls(1)
        self.assertEqual(prepare[2], 128)  # index_mcp_pitch

    def test_level1_prepare_other_fingers_open(self):
        prepare, _ = self._run_and_get_move_calls(1)
        for idx in [3, 4, 5]:
            self.assertEqual(prepare[idx], 0)

    def test_level1_grasp_thumb_pitch_in(self):
        _, grasp = self._run_and_get_move_calls(1)
        self.assertEqual(grasp[0], 255)  # thumb_cmc_pitch

    def test_level1_grasp_thumb_yaw_in(self):
        _, grasp = self._run_and_get_move_calls(1)
        self.assertEqual(grasp[1], 255)  # thumb_cmc_yaw

    def test_level1_grasp_index_full(self):
        _, grasp = self._run_and_get_move_calls(1)
        self.assertEqual(grasp[2], 255)  # index_mcp_pitch

    def test_level1_grasp_other_fingers_open(self):
        _, grasp = self._run_and_get_move_calls(1)
        for idx in [3, 4, 5]:
            self.assertEqual(grasp[idx], 0)

    def test_level2_prepare_index_and_middle_half(self):
        prepare, _ = self._run_and_get_move_calls(2)
        self.assertEqual(prepare[2], 128)  # index
        self.assertEqual(prepare[3], 128)  # middle

    def test_level2_prepare_ring_open(self):
        prepare, _ = self._run_and_get_move_calls(2)
        self.assertEqual(prepare[4], 0)

    def test_level2_grasp_index_and_middle_full(self):
        _, grasp = self._run_and_get_move_calls(2)
        self.assertEqual(grasp[2], 255)
        self.assertEqual(grasp[3], 255)

    def test_level2_grasp_ring_open(self):
        _, grasp = self._run_and_get_move_calls(2)
        self.assertEqual(grasp[4], 0)

    def test_level3_prepare_index_middle_ring_half(self):
        prepare, _ = self._run_and_get_move_calls(3)
        self.assertEqual(prepare[2], 128)  # index
        self.assertEqual(prepare[3], 128)  # middle
        self.assertEqual(prepare[4], 128)  # ring

    def test_level3_prepare_pinky_open(self):
        prepare, _ = self._run_and_get_move_calls(3)
        self.assertEqual(prepare[5], 0)

    def test_level3_grasp_index_middle_ring_full(self):
        _, grasp = self._run_and_get_move_calls(3)
        self.assertEqual(grasp[2], 255)
        self.assertEqual(grasp[3], 255)
        self.assertEqual(grasp[4], 255)

    def test_level3_grasp_pinky_open(self):
        _, grasp = self._run_and_get_move_calls(3)
        self.assertEqual(grasp[5], 0)

    def test_level4_prepare_only_thumb_yaw(self):
        prepare, _ = self._run_and_get_move_calls(4)
        self.assertEqual(prepare[1], 255)  # thumb_cmc_yaw
        for idx in [0, 2, 3, 4, 5]:
            self.assertEqual(prepare[idx], 0)

    def test_level4_grasp_all_pitch_joints_in(self):
        _, grasp = self._run_and_get_move_calls(4)
        self.assertEqual(grasp[0], 255)  # thumb_cmc_pitch
        self.assertEqual(grasp[1], 255)  # thumb_cmc_yaw
        self.assertEqual(grasp[2], 255)  # index
        self.assertEqual(grasp[3], 255)  # middle
        self.assertEqual(grasp[4], 255)  # ring
        self.assertEqual(grasp[5], 255)  # pinky

    def test_level4_grasp_all_joints_fully_closed(self):
        _, grasp = self._run_and_get_move_calls(4)
        self.assertTrue(all(v == 255 for v in grasp))

    def test_poses_are_length_6(self):
        for level in (1, 2, 3, 4):
            poses = self._run_and_get_move_calls(level)
            for pose in poses:
                self.assertEqual(len(pose), 6)


class TestGraspActionDispatch(_GraspTestMixin, unittest.TestCase):
    """Tests for controller dispatch: set_torque, prepare move, grasp move."""

    def test_set_torque_called_first(self):
        action = self._make(torque_limit=150)
        action.start()
        action.wait(timeout=2.0)
        first_call = self._controller.execute.call_args_list[0]
        self.assertEqual(first_call[0][1], "set_torque")

    def test_set_torque_uses_correct_device(self):
        action = self._make(device_name="right_hand", torque_limit=100)
        action.start()
        action.wait(timeout=2.0)
        first_call = self._controller.execute.call_args_list[0]
        self.assertEqual(first_call[0][0], "right_hand")

    def test_set_torque_value_repeated_6_times(self):
        action = self._make(torque_limit=200)
        action.start()
        action.wait(timeout=2.0)
        first_call = self._controller.execute.call_args_list[0]
        self.assertEqual(first_call[0][2], [200] * 6)

    def test_prepare_move_dispatched_to_correct_device(self):
        action = self._make(device_name="my_hand")
        action.start()
        action.wait(timeout=2.0)
        prepare_call = self._controller.execute.call_args_list[1]
        self.assertEqual(prepare_call[0][0], "my_hand")
        self.assertEqual(prepare_call[0][1], "move")

    def test_grasp_move_dispatched_to_correct_device(self):
        action = self._make(device_name="my_hand")
        action.start()
        action.wait(timeout=2.0)
        grasp_call = self._controller.execute.call_args_list[2]
        self.assertEqual(grasp_call[0][0], "my_hand")
        self.assertEqual(grasp_call[0][1], "move")

    def test_total_execute_calls_is_three(self):
        action = self._make()
        action.start()
        action.wait(timeout=2.0)
        self.assertEqual(self._controller.execute.call_count, 3)

    def test_result_is_true_on_success(self):
        action = self._make()
        action.start()
        action.wait(timeout=2.0)
        self.assertEqual(action.state(), ActionState.DONE)
        self.assertTrue(action.result())

    def test_set_torque_failure_sets_failed_state(self):
        self._controller.execute.side_effect = [False]
        action = self._make()
        action.start()
        action.wait(timeout=2.0)
        self.assertEqual(action.state(), ActionState.FAILED)
        self.assertIsInstance(action.error(), RuntimeError)

    def test_prepare_move_failure_sets_failed_state(self):
        self._controller.execute.side_effect = [True, False]
        action = self._make()
        action.start()
        action.wait(timeout=2.0)
        self.assertEqual(action.state(), ActionState.FAILED)
        self.assertIsInstance(action.error(), RuntimeError)

    def test_grasp_move_failure_sets_failed_state(self):
        self._controller.execute.side_effect = [True, True, False]
        action = self._make()
        action.start()
        action.wait(timeout=2.0)
        self.assertEqual(action.state(), ActionState.FAILED)
        self.assertIsInstance(action.error(), RuntimeError)


class TestGraspActionCheckpoint(_GraspTestMixin, unittest.TestCase):
    """Tests for cooperative pause/cancel between grasp phases."""

    def _blocking_execute(self, n):
        """Return (side_effect, at_call_events, proceed_events) for n calls."""
        at_call = [threading.Event() for _ in range(n)]
        proceed = [threading.Event() for _ in range(n)]
        idx = [0]

        def side_effect(*args, **kwargs):
            i = idx[0]
            idx[0] += 1
            at_call[i].set()
            proceed[i].wait()
            return True

        return side_effect, at_call, proceed

    def test_cancel_between_phases_stops_grasp_move(self):
        side_effect, at_call, proceed = self._blocking_execute(3)
        self._controller.execute.side_effect = side_effect
        action = self._make()
        action.start()
        at_call[0].wait()  # set_torque in progress
        proceed[0].set()
        at_call[1].wait()  # prepare move in progress
        action.cancel()
        proceed[1].set()
        action.wait(timeout=2.0)
        self.assertEqual(action.state(), ActionState.CANCELLED)
        self.assertEqual(self._controller.execute.call_count, 2)

    def test_cancel_returns_false_result(self):
        side_effect, at_call, proceed = self._blocking_execute(3)
        self._controller.execute.side_effect = side_effect
        action = self._make()
        action.start()
        at_call[0].wait()  # set_torque in progress
        proceed[0].set()
        at_call[1].wait()  # prepare move in progress
        action.cancel()
        proceed[1].set()
        action.wait(timeout=2.0)
        self.assertFalse(action.result())

    def test_pause_between_phases_blocks_grasp_until_resume(self):
        side_effect, at_call, proceed = self._blocking_execute(3)
        self._controller.execute.side_effect = side_effect
        action = self._make()
        action.start()
        at_call[0].wait()
        proceed[0].set()
        at_call[1].wait()
        action.pause()
        proceed[1].set()
        self.assertFalse(at_call[2].wait(timeout=0.1))
        action.resume()
        at_call[2].wait()
        proceed[2].set()
        self.assertTrue(action.wait(timeout=2.0))
        self.assertEqual(action.state(), ActionState.DONE)

    def test_cancel_after_grasp_move_produces_cancelled_or_done(self):
        side_effect, at_call, proceed = self._blocking_execute(3)
        self._controller.execute.side_effect = side_effect
        action = self._make()
        action.start()
        at_call[0].wait()
        proceed[0].set()
        at_call[1].wait()
        proceed[1].set()
        at_call[2].wait()
        action.cancel()
        proceed[2].set()
        action.wait(timeout=2.0)
        self.assertIn(action.state(), (ActionState.CANCELLED, ActionState.DONE))


if __name__ == "__main__":
    unittest.main()
